### ISSUE TITLE
i get this while logging in

### ISSUE THREAD

**Issue by DARKgod2** [MS-Jahan/Messenger-Message-Logger#2]
Traceback (most recent call last):
  File "main.py", line 530, in <module>
    login_logout()
  File "main.py", line 59, in login_logout
    client = CustomClient(email, password, max_tries=1)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\fbchat\_client.py", line 103, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\fbchat\_client.py", line 209, in login
    user_agent=user_agent,
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\fbchat\_state.py", line 149, in login
    return cls.from_session(session=session)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\fbchat\_state.py", line 188, in from_session
    revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])
IndexError: list index out of range

**Comment by MS-Jahan** [comment]
It's an issue related with fbchat module, not my script. See the issue [here](https://github.com/fbchat-dev/fbchat/issues/619).

**Comment by MS-Jahan** [comment]
Issue is solved here: https://github.com/fbchat-dev/fbchat/issues/615#issuecomment-716089816
