### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by P3ridot** [MS-Jahan/Messenger-Message-Logger#8]
```
Logging in mymail@facebook.com...
s\0000
Traceback (most recent call last):
  File "main.py", line 527, in <module>
    login_logout()
  File "main.py", line 64, in login_logout
    client = CustomClient(email, password, max_tries=1)
  File "/usr/local/lib/python3.7/dist-packages/fbchat/_client.py", line 103, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "/usr/local/lib/python3.7/dist-packages/fbchat/_client.py", line 209, in login
    user_agent=user_agent,
  File "/usr/local/lib/python3.7/dist-packages/fbchat/_state.py", line 157, in login
    code = on_2fa_callback()
  File "main.py", line 207, in on2FACode
    temp = otp.get_totp(otp_key)
  File "/home/mlogger/.local/lib/python3.7/site-packages/onetimepass/__init__.py", line 169, in get_totp
    token_length=token_length,
  File "/home/mlogger/.local/lib/python3.7/site-packages/onetimepass/__init__.py", line 113, in get_hotp
    key = base64.b32decode(secret, casefold=casefold)
  File "/usr/lib/python3.7/base64.py", line 205, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding
```

**Comment by P3ridot** [comment]
Putting empty string in opt_key fixed issue
